config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :user do
  post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
end

  root to: 'public/homes#top'

  scope module: :public do
    get 'about' => 'homes#about', as: 'about'
    get 'privacy_policy' => 'homes#privacy_policy', as: 'privacy_policy'
    resources :records, only: [:index]
    resources :record_tea_leaves, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :record_coffees, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :searches, only: [:index] do
      collection do
        get :search
      end
    end

    get 'users/mypage' => 'users#index'
    get 'users/setting/edit' => 'users#edit'
    patch 'users/setting' => 'users#update'
    get 'users/confirm' => 'users#confirm'
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/:id' => 'users#show', as: 'users/record'
    get 'favorites_coffee' => 'favorites#coffee_list'
    get 'favorites_tea' => 'favorites#tea_list'
    get 'search_coffeetags' => 'record_coffees#search'
    get 'search_teatags' => 'record_tea_leaves#search'
  end

  namespace :admin do
    get '/' => 'homes#top'
    get 'search_coffeetags' => 'record_coffees#search'
    get 'search_teatags' => 'record_tea_leaves#search'
    get 'search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update]
    resources :record_coffees, only: [:index, :show, :edit, :update, :destroy]
    resources :record_tea_leaves, only: [:index, :show, :edit, :update, :destroy]
    resources :tags, only: [:index, :edit, :update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/record_tea_leaves_controller.rb
class Admin::RecordTeaLeavesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @record_tea_leaves = RecordTeaLeafe.all.page(params[:page]).per(10)
  end

  def show
    @record_tea_leafe = RecordTeaLeafe.find(params[:id])
    @user = User.find(@record_tea_leafe.user[:id])
    @tag_list = @record_tea_leafe.tags.pluck(:name).join(',')
    @record_tea_leafe_tags = @record_tea_leafe.tags
    @comment = Comment.new
  end

  def edit
    @record_tea_leafe = RecordTeaLeafe.find(params[:id])
    @tag_list = @record_tea_leafe.tags.pluck(:name).join(',')
  end

  def update
    @record_tea_leafe = RecordTeaLeafe.find(params[:id])
    tag_list = params[:record_tea_leafe][:tag].split(',')
    if @record_tea_leafe.update(record_tea_leafe_params)
      @record_tea_leafe.save_tags(tag_list)
      redirect_to admin_record_tea_leafe_path(@record_tea_leafe), notice: "変更を保存しました"
    else
      render :edit
    end
  end
  
  def search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @taggings = Tagging.where(tag_id: params[:tag_id])
    @tea_taggings = @taggings.where(record_drinkable_type: "RecordTeaLeafe")
    @record_tea_leaves = @tag.record_tea_leaves.page(params[:page]).per(10)
  end



    private

  def record_tea_leafe_params
    params.require(:record_tea_leafe).permit(

      :item_name,
      :shop_name,
      :price,
      :review,
      :total_star,
      :scent_star,
      :sweet_star,
      :astringency_star,
      :fresh_star,
      :easy_star,
      :release,
      :tag_id,
      :image
    )
  end

end

app/helpers/admin/record_tea_leaves_helper.rb
module Admin::RecordTeaLeavesHelper
end

app/views/admin/record_tea_leaves/_index.html.erb
    <table class='table table-hover table-light-0 margin-y'>
      <thead>
        <tr>
          <th>投稿日時</th>
          <th>投稿者</th>
          <th>商品名</th>
          <th>ショップ名</th>
          <th>公開/非公開</th>
        </tr>
      </thead>
      <tbody>
        <% @record_tea_leaves.each do |record_tea_leafe| %>
        <tr>
          <td><%= link_to record_tea_leafe.created_at.strftime('%Y/%m/%d'), admin_record_tea_leafe_path(record_tea_leafe.id) %></td>
          <td><%= record_tea_leafe.user.name %></td>
          <td><%= record_tea_leafe.item_name %></td>
          <td><%= record_tea_leafe.shop_name %></td>
          <td>
            <% if record_tea_leafe.release %>
              <span>公開</span>
            <% else %>
              <span>非公開</span>
            <% end %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/admin/record_tea_leaves/edit.html.erb
<div class="container w-75">
  <div class="background-board py-3 px-5 my-4">
      <h4 class="h4-create mb-5">Tea Review編集</h4>
        <%= render 'layouts/errors', obj: @record_tea_leafe %>
      <div class="col-10 mx-auto">
        <%= form_with model: @record_tea_leafe, url: admin_record_tea_leafe_path do |f| %>
          <%= render 'public/record_tea_leaves/tea_form', f: f %>
        <div class="form-group">
          <%= f.submit '変更を保存', class: "btn btn-success  mx-auto my-3 d-block" %>
        </div>
        <% end %>
      </div>
  </div>
</div>

app/views/admin/record_tea_leaves/index.html.erb
<div class="container w-75">
  <div class="background-board py-3 px-5 my-4">
    <%= render 'admin/searches/search' %>
  </div>
  <div class="background-board py-3 px-5 my-4">
  <div class="margin-y">
    <div class="d-flex align-items-center justify-content-between">
      <h4 class="h4-review mb-4">Tea Review一覧</h4>
    </div>
    <%= link_to "Coffee", admin_record_coffees_path %> | <%= link_to "Tea", admin_record_tea_leaves_path %>
    <%= render 'admin/record_tea_leaves/index', record_tea_leafe: @record_tea_leafe %>
  </div>
  <%= paginate @record_tea_leaves %>
  </div>
</div>

app/views/admin/record_tea_leaves/search.html.erb
<div class="container w-75">
  <div class="background-board py-3 px-5 my-4">
    <div class="d-flex align-items-center justify-content-between">
      <h4 class="h4-review mb-5">タグが"<%= @tag.name %>"のTea Review</h4>
    </div>
      <%= render 'admin/record_tea_leaves/index', record_tea_leafe: @record_tea_leafe %>
    <%= paginate @record_tea_leaves %>
  </div>
</div>

app/views/admin/record_tea_leaves/show.html.erb
<div class="container w-75">
  <div class="background-board py-3 px-5 my-4">
    <div class="d-flex align-items-center justify-content-between">
      <h4 class="h4-review mb-5">Tea Review</h4>
    </div>
    <table class='table table-light-0 margin-y'>
        <tr>
          <td>レビューID</td>
          <td><%= @record_tea_leafe.id %></td>
        </tr>
        <tr>
          <td>ユーザー名</td>
          <td><%= @record_tea_leafe.user.name %></td>
        </tr>
        <tr>
          <td>商品名</td>
          <td><%= @record_tea_leafe.item_name %></td>
        </tr>
        <tr>
          <td>ショップ名</td>
          <td><%= @record_tea_leafe.shop_name %></td>
        </tr>
          <tr>
          <td>価格</td>
          <td><%= @record_tea_leafe.price.to_s(:delimited) %>円(税込/100gあたり)</td>
        </tr>
        <tr>
          <td>タグ</td>
          <td>
            <% @record_tea_leafe_tags.each do |tag| %>
              <i class="fa-sharp fa-solid fa-tag"></i>
              <%= link_to tag.name, admin_search_teatags_path(tag_id: tag.id) %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>評価</td>
          <td><%= render 'public/record_tea_leaves/star_result', record_tea_leafe: @record_tea_leafe %></td>
        </tr>
        <tr>
          <td>レビュー</td>
          <td><%= @record_tea_leafe.review %></td>
        </tr>
        <tr>
          <td>公開/非公開</td>
          <td>
          <% if @record_tea_leafe.release %>
            <span>公開</span>
          <% else %>
            <span>非公開</span>
          <% end %>
          </td>
        </tr>
    </table>

    <div class="d-flex justify-content-around">
      <%= link_to "一覧に戻る", admin_record_tea_leaves_path, class: "btn btn-primary" %>
      <%= link_to "編集する", edit_admin_record_tea_leafe_path(@record_tea_leafe), class: "btn btn-success" %>
    </div>
  </div>
</div>