config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :user do
  post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
end

  root to: 'public/homes#top'

  scope module: :public do
    get 'about' => 'homes#about', as: 'about'
    get 'privacy_policy' => 'homes#privacy_policy', as: 'privacy_policy'
    resources :records, only: [:index]
    resources :record_tea_leaves, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :record_coffees, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :searches, only: [:index] do
      collection do
        get :search
      end
    end

    get 'users/mypage' => 'users#index'
    get 'users/setting/edit' => 'users#edit'
    patch 'users/setting' => 'users#update'
    get 'users/confirm' => 'users#confirm'
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/:id' => 'users#show', as: 'users/record'
    get 'favorites_coffee' => 'favorites#coffee_list'
    get 'favorites_tea' => 'favorites#tea_list'
    get 'search_coffeetags' => 'record_coffees#search'
    get 'search_teatags' => 'record_tea_leaves#search'
  end

  namespace :admin do
    get '/' => 'homes#top'
    get 'search_coffeetags' => 'record_coffees#search'
    get 'search_teatags' => 'record_tea_leaves#search'
    get 'search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update]
    resources :record_coffees, only: [:index, :show, :edit, :update, :destroy]
    resources :record_tea_leaves, only: [:index, :show, :edit, :update, :destroy]
    resources :tags, only: [:index, :edit, :update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/record_coffee.rb
class RecordCoffee < ApplicationRecord

  has_one_attached :image

  belongs_to :user
  has_many :comments, dependent: :destroy, as: :record_drinkable
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :taggings, dependent: :destroy, as: :record_drinkable
  has_many :tags, through: :taggings

  validates :item_name, presence:true
  validates :shop_name, presence:true
  validates :price, presence:true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :review, presence:true, length: { minimum: 10, maximum: 500}
  validates :total_star, presence:true

  scope :latest, -> {order(created_at: :desc)}
  scope :total_star_count, -> {order(total_star: :desc)}
  scope :released, -> {where(release: true)}
  scope :unreleased, -> {where(release: false)}

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  #tag作成・更新
  def save_tags(tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    new_tags.each do |new_name|
      tag = Tag.find_or_create_by(name:new_name)
      self.tags << tag
    end
  end

  def self.looks(search, word)
    if search == "item_name"
      @record_coffee = RecordCoffee.where("item_name LIKE?", "%#{word}%")
    elsif search == "shop_name"
      @record_coffee = RecordCoffee.where("shop_name LIKE?", "%#{word}%")
    else
      @record_coffee = RecordCoffee.all
    end
  end


end

app/controllers/admin/record_coffees_controller.rb
class Admin::RecordCoffeesController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @record_coffees = RecordCoffee.all.page(params[:page]).per(10)
  end

  def show
    @record_coffee = RecordCoffee.find(params[:id])
    @user = User.find(@record_coffee.user[:id])
    @tag_list = @record_coffee.tags.pluck(:name).join(',')
    @record_coffee_tags = @record_coffee.tags
    @comment = Comment.new
  end

  def edit
    @record_coffee = RecordCoffee.find(params[:id])
    @tag_list = @record_coffee.tags.pluck(:name).join(',')
  end
  
  def update
    @record_coffee = RecordCoffee.find(params[:id])
    tag_list = params[:record_coffee][:tag].split(',')
    if @record_coffee.update(record_coffee_params)
      @record_coffee.save_tags(tag_list)
      redirect_to admin_record_coffee_path(@record_coffee), notice: "変更を保存しました"
    else
      render :edit
    end
  end
  
  def search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @taggings = Tagging.where(tag_id: params[:tag_id])
    @coffee_taggings = @taggings.where(record_drinkable_type: "RecordCoffee")
    @record_coffees = @tag.record_coffees.page(params[:page]).per(10)
  end
  
  
   private

  def record_coffee_params
    params.require(:record_coffee).permit(
      :item_name,
      :shop_name,
      :price,
      :review,
      :total_star,
      :scent_star,
      :bitter_star,
      :acidity_star,
      :sweet_star,
      :rich_star,
      :release,
      :tag_id,
      :image
    )
  end
  
end

app/helpers/admin/record_coffees_helper.rb
module Admin::RecordCoffeesHelper
end

app/views/admin/record_coffees/_index.html.erb
   <table class='table table-hover table-light-0 margin-y'>
      <thead>
        <tr>
          <th>投稿日時</th>
          <th>投稿者</th>
          <th>商品名</th>
          <th>ショップ名</th>
          <th>公開/非公開</th>
        </tr>
      </thead>
      <tbody>
        <% @record_coffees.each do |record_coffee| %>
        <tr>
          <td><%= link_to record_coffee.created_at.strftime('%Y/%m/%d'), admin_record_coffee_path(record_coffee.id) %></td>
          <td><%= record_coffee.user.name %></td>
          <td><%= record_coffee.item_name %></td>
          <td><%= record_coffee.shop_name %></td>
          <td>
            <% if record_coffee.release %>
              <span>公開</span>
            <% else %>
              <span>非公開</span>
            <% end %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/admin/record_coffees/edit.html.erb
<div class="container w-75">
  <div class="background-board py-3 px-5 my-4">
      <h4 class="h4-create mb-5">Coffee Review編集</h4>
        <%= render 'layouts/errors', obj: @record_coffee %>
      <div class="col-10 mx-auto">
        <%= form_with model: @record_coffee, url: admin_record_coffee_path do |f| %>
          <%= render 'public/record_coffees/coffee_form', f: f %>
        <div class="form-group">
          <%= f.submit '変更を保存', class: "btn btn-success  mx-auto my-3 d-block" %>
        </div>
        <% end %>
      </div>
  </div>
</div>

app/views/admin/record_coffees/index.html.erb
<div class="container w-75">
  <div class="background-board py-3 px-5 my-4">
    <%= render 'admin/searches/search' %>
  </div>
  <div class="background-board py-3 px-5 my-4">
    <div class="margin-y">
      <div class="d-flex align-items-center justify-content-between">
        <h4 class="h4-review mb-4">Coffee Review投稿一覧</h4>
      </div>
      <%= link_to "Coffee", admin_record_coffees_path %> | <%= link_to "Tea", admin_record_tea_leaves_path %>
      <%= render 'admin/record_coffees/index', record_coffee: @record_coffee %>
    </div>
  <%= paginate @record_coffees %>
  </div>
</div>

app/views/admin/record_coffees/search.html.erb
<div class="container w-75">
  <div class="background-board py-3 px-5 my-4">
    <div class="d-flex align-items-center justify-content-between">
      <h4 class="h4-review mb-5">タグが"<%= @tag.name %>"のCoffee Review</h4>
    </div>
      <%= render 'admin/record_coffees/index', record_coffee: @record_coffee %>
    <%= paginate @record_coffees %>
  </div>
</div>

app/views/admin/record_coffees/show.html.erb
<div class="container w-75">
  <div class="background-board py-3 px-5 my-4">
    <div class="d-flex align-items-center justify-content-between">
      <h4 class="h4-review mb-5">Coffee Review</h4>
    </div>
    <table class='table table-light-0 margin-y'>
        <tr>
          <td>レビューID</td>
          <td><%= @record_coffee.id %></td>
        </tr>
        <tr>
          <td>ユーザー名</td>
          <td><%= @record_coffee.user.name %></td>
        </tr>
        <tr>
          <td>商品名</td>
          <td><%= @record_coffee.item_name %></td>
        </tr>
        <tr>
          <td>ショップ名</td>
          <td><%= @record_coffee.shop_name %></td>
        </tr>
          <tr>
          <td>価格</td>
          <td><%= @record_coffee.price.to_s(:delimited) %>円(税込/100gあたり)</td>
        </tr>
        <tr>
          <td>タグ</td>
          <td>
            <% @record_coffee_tags.each do |tag| %>
              <i class="fa-sharp fa-solid fa-tag"></i>
              <%= link_to tag.name, admin_search_coffeetags_path(tag_id: tag.id) %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>評価</td>
          <td><%= render 'public/record_coffees/star_result', record_coffee: @record_coffee %></td>
        </tr>
        <tr>
          <td>レビュー</td>
          <td><%= @record_coffee.review %></td>
        </tr>
        <tr>
          <td>公開/非公開</td>
          <td>
          <% if @record_coffee.release %>
            <span>公開</span>
          <% else %>
            <span>非公開</span>
          <% end %>
          </td>
        </tr>
    </table>

    <div class="d-flex justify-content-around">
      <%= link_to "一覧に戻る", admin_record_coffees_path, class: "btn btn-primary" %>
      <%= link_to "編集する", edit_admin_record_coffee_path(@record_coffee), class: "btn btn-success" %>
    </div>
  </div>
</div>