config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :user do
  post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
end

  root to: 'public/homes#top'

  scope module: :public do
    get 'about' => 'homes#about', as: 'about'
    get 'privacy_policy' => 'homes#privacy_policy', as: 'privacy_policy'
    resources :records, only: [:index]
    resources :record_tea_leaves, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :record_coffees, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :searches, only: [:index] do
      collection do
        get :search
      end
    end

    get 'users/mypage' => 'users#index'
    get 'users/setting/edit' => 'users#edit'
    patch 'users/setting' => 'users#update'
    get 'users/confirm' => 'users#confirm'
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/:id' => 'users#show', as: 'users/record'
    get 'favorites_coffee' => 'favorites#coffee_list'
    get 'favorites_tea' => 'favorites#tea_list'
    get 'search_coffeetags' => 'record_coffees#search'
    get 'search_teatags' => 'record_tea_leaves#search'
  end

  namespace :admin do
    get '/' => 'homes#top'
    get 'search_coffeetags' => 'record_coffees#search'
    get 'search_teatags' => 'record_tea_leaves#search'
    get 'search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update]
    resources :record_coffees, only: [:index, :show, :edit, :update, :destroy]
    resources :record_tea_leaves, only: [:index, :show, :edit, :update, :destroy]
    resources :tags, only: [:index, :edit, :update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :record_coffees, dependent: :destroy
  has_many :record_tea_leaves, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20}



  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/profile_no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename:'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
   before_action :authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: "変更を保存しました"
    else
      render :edit
    end
  end

    private

  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :is_deleted)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container w-75">
  <div class="background-board py-3 px-5 my-4">
      <h4 class="h4-create mb-5">ユーザー登録情報編集</h4>
        <%= render 'layouts/errors', obj: @user %>
      <div class="col-10 mx-auto">
        <%= form_with model: @user, url: admin_user_path do |f| %>
          <div class="form-group">
            <div class="d-flex flex-row mb-3">
              <div class="col-3">
                <%= f.label :name, 'ユーザー名' %>
              </div>
              <div class="col-6">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="d-flex flex-row mb-3">
              <div class="col-3">
                <%= f.label :image, 'アイコン' %>
              </div>
              <div class="col-6">
                <%= f.file_field :profile_image, class: "form-control-file", accept: 'image/*' %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="d-flex flex-row mb-3">
              <div class="col-3">
                <%= f.label :email, 'メールアドレス'%>
              </div>
              <div class="col-6">
                <%= f.text_field :email, class: "form-control" %>
              </div>
            </div>
            <div class="d-flex flex-row mb-3">
              <div class="col-3">
                <p class="label-width label-name ">ユーザーステータス</p>
              </div>
              <div class="col-6">
                <div class="d-flex justify-content-around">
                <span class="margin-x">
                  <%= f.radio_button :is_deleted, false %>
                　<%= f.label :is_deleted, "有効", {value: :false} %>
                </span>
                <span class="ml-5">
                  <%= f.radio_button :is_deleted, true %>
                　<%= f.label :is_deleted, "退会", {value: :true} %>
                </span>
                </div>
              </div>
            </div>
          </div>
      <div class="form-group">
        <%= f.submit '変更を保存', class: "btn btn-success  mx-auto my-3 d-block" %>
      </div>
        <% end %>
      </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container w-75">
  <div class="background-board py-3 px-5 my-4">
    <div class="margin-y">
      <h4 class="h4-search mb-4">ユーザー一覧</h4>
    <table class='table table-hover table-light-0 margin-y'>
      <thead>
        <tr>
          <th>ユーザーID</th>
          <th>ユーザー名</th>
          <th>メールアドレス</th>
          <th>ユーザーステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= link_to user.name, admin_user_path(user.id) %></td>
            <td><%= user.email %></td>
            <td>
              <% if user.is_deleted %>
                <span class="text-muted">退会済み</span>
              <% else %>
                <span class="text-success"><strong>有効</strong></span>
              <% end %>
            </td>
          </tr>
        <% end %>
    </table>
    </div>
  <%= paginate @users %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container w-75">
  <div class="background-board py-3 px-5 my-4">
    <div class="d-flex align-items-center justify-content-between">
      <h4 class="h4-review mb-5"><%= @user.name %>さんの登録詳細</h4>
    </div>
    <div class="col-10 mb-3 mx-auto">
      <table class='table table-hover table-light-0 margin-y'>
        <tr>
          <td>ユーザーID</td>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <td>ユーザー名</td>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td>ユーザーステータス</td>
          <td>
            <% if @user.is_deleted %>
              <strong class="text-danger">退会</strong>
            <% else %>
              <strong class="text-success">有効</strong>
            <% end %>
          </td>
        </tr>
    </table>

    <div class="d-flex justify-content-around">
      <%= link_to "一覧に戻る", admin_users_path, class: "btn btn-primary" %>
      <%= link_to "編集する", edit_admin_user_path(@user), class: "btn btn-success" %>
    </div>
  </div>
</div>