config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :user do
  post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
end

  root to: 'public/homes#top'

  scope module: :public do
    get 'about' => 'homes#about', as: 'about'
    get 'privacy_policy' => 'homes#privacy_policy', as: 'privacy_policy'
    resources :records, only: [:index]
    resources :record_tea_leaves, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :record_coffees, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :searches, only: [:index] do
      collection do
        get :search
      end
    end

    get 'users/mypage' => 'users#index'
    get 'users/setting/edit' => 'users#edit'
    patch 'users/setting' => 'users#update'
    get 'users/confirm' => 'users#confirm'
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/:id' => 'users#show', as: 'users/record'
    get 'favorites_coffee' => 'favorites#coffee_list'
    get 'favorites_tea' => 'favorites#tea_list'
    get 'search_coffeetags' => 'record_coffees#search'
    get 'search_teatags' => 'record_tea_leaves#search'
  end

  namespace :admin do
    get '/' => 'homes#top'
    get 'search_coffeetags' => 'record_coffees#search'
    get 'search_teatags' => 'record_tea_leaves#search'
    get 'search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update]
    resources :record_coffees, only: [:index, :show, :edit, :update, :destroy]
    resources :record_tea_leaves, only: [:index, :show, :edit, :update, :destroy]
    resources :tags, only: [:index, :edit, :update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
 <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand mx-3" href="/"><%= image_tag 'logo_white.png', style: "width: 90px" %></a>
              <% if user_signed_in? %>
                <p class="m-0 text-light"><%= current_user.name %>さん</p>
              <% end %>
              <% if admin_signed_in? %>
                <h6 class="m-0 text-light">管理者画面</h6>
              <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item px-2">
                <%= link_to "Top", '/', class: 'nav-link text-light' %>
              </li>
              <li class="nav-item px-2">
                <%= link_to "About", about_path, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item dropdown px-2">
              <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Review
              </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="/record_coffees">Coffee Review</a></li>
                  <li><a class="dropdown-item" href="/record_tea_leaves">Tea Review</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown px-2">
              <a class="nav-link dropdown-toggle text-light" href="/users/mypage" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Mypage
              </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="/users/mypage">Mypage Top</a></li>
                  <li><a class="dropdown-item" href="/record_coffees/new">Coffee New Review</a></li>
                  <li><a class="dropdown-item" href="/record_tea_leaves/new">Tea New Review</a></li>
                  <li><a class="dropdown-item" href="/favorites_coffee">Favorite Coffee</a></li>
                  <li><a class="dropdown-item" href="/favorites_tea">Favorite Tea</a></li>
                </ul>
              </li>
              <li class="nav-item px-2">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item dropdown px-2">
              <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Review
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/admin/record_coffees">Coffee Review</a></li>
                <li><a class="dropdown-item" href="/admin/record_tea_leaves">Tea Review</a></li>
              </ul>
              </li>
              <li class="nav-item px-2">
                <%= link_to "User List", admin_users_path, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item px-2">
                <%= link_to "Log out", destroy_admin_session_path, method: :delete, class: 'nav-link text-light'%>
              </li>
            <% else %>
              <li class="nav-item px-2">
                <%= link_to "Top", '/', class: 'nav-link text-light' %>
              </li>
              <li class="nav-item px-2">
                <%= link_to "About", about_path, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item px-2">
                <%= link_to "Sign in", new_user_registration_path, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item px-2">
                <%= link_to "Log in", new_user_session_path, class: 'nav-link text-light' %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeRec</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximun-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/192d4374d3.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="cover-img mx-auto" style="background-image:url(<%= asset_path 'top2.jpg' %>);">
      <div class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>

    <main class="mb-auto">
      <% if flash[:notice].present? %>
    <div class="error_messages text-center margin-y">
      <%= flash[:notice]%>
    </div>
      <% end %>
    <%= yield %>
    </main>
    <footer class="text-white pt-3 pb-2"  style="background-color: #40290E;">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-12 px-5">
            <div class="d-flex justify-content-center mb-2">
              <%= link_to '当サイトについて', about_path, class:"text-white small mr-3" %>
              <%= link_to 'プライバシーポリシー', privacy_policy_path, class:"text-white small" %>
            </div>
            <p class="small text-center"><i class="fa-sharp fa-regular fa-copyright"></i>CopyRight Cafe rec.</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>